### ISSUE TITLE
Покрытие тестами

### ISSUE THREAD

**Issue by ChALkeR** [ovchinnikov94/js_learn_node#1]
Несколько замечаний:
1. Директория `coverage` в проекте не нужна, она создаётся автоматически при вычислении покрытияя. Стоит её удалить и добавить в `.gitignore`.
2. У вас ошибка в `.istanbul.yml` [на строке 3](https://github.com/ovchinnikov94/chat_nodejs/blob/master/.istanbul.yml#L3). `instrumentation.root` — это корневая директория вашего кода, к которому будет применяться предварительная обработка для анализа покрытия. В вашем случае там должна быть либо текущая директория (`.`), либо `./libs`, либо можно вообще этот параметр исключить (там по умолчанию текущая директория).
3. В `https://github.com/ovchinnikov94/chat_nodejs/blob/master/package.json#L7` вместо `mocha` надо вызвать `_mocha` — первый форкается и это мешает истанбулу. `_mocha` лежит в  `./node_modules/mocha/bin/_mocha`.
4. У вас ошибки в тестах — некоторые переменные не определены. Babel добавит `use strict` и тесты упадут.

Если всё это исправить — тесты начинают работать.

**Comment by ChALkeR** [comment]
И да:
1. `gulp.task('test', function(){});` не нужен, так как у вас тесты вызываются другой командой.
2. У вас используется `babel-preset-es2015`, но, во-первых, нет от него зависимости, а во-вторых он не очень нужен, так как вы можете использовать пресет, который конвертирует только то, чего нету в той (минимальной) версии Node.js, под которую вы хотите работать. Например, `babel-preset-es2015-node4` или `babel-preset-es2015-node6`.

Кстати, в недавно вышедшем Node.js 6 есть целая куча новых фич из es2015, так что [babel-preset-es2015-node6](https://www.npmjs.com/package/babel-preset-es2015-node6) это, по сути, три плагина.

**Comment by ovchinnikovdk** [comment]
@ChALkeR 
Замечания исправил. 
Теперь проблема следующая: 
Travis CI валится на установке зависимостей, потому что использует не C11 стандарт компилятора. Нашел решение в документации [https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-%28or-io.js-v3%29-compiler-requirements](url) 

Но это не помогает...

**Comment by ChALkeR** [comment]
@ovchinnikov94 М? У вас на https://travis-ci.org/ovchinnikov94/chat_nodejs, вроде, всё собралось?

**Comment by ovchinnikovdk** [comment]
@ChALkeR Все собралось, спасибо!
