### ISSUE TITLE
Сборка на Travis не проходит тесты.

### ISSUE THREAD

**Issue by ChALkeR** [ovchinnikov94/js_learn_node#2]
По-моему, у вас там просто базы данных нет.
См. https://docs.travis-ci.com/user/database-setup/

И да, добавьте в описание (README.md) бейджик трависа, чтобы можно было быстро перейти (и увидеть статус).

**Comment by ovchinnikovdk** [comment]
@ChALkeR Добавил базу данных и бэйджик! Спасибо!
