### ISSUE TITLE
Eslint

### ISSUE THREAD

**Issue by ChALkeR** [ovchinnikov94/js_learn_node#4]
Можете добавить проверку синтаксиса через eslint?
Можно либо вручную накидать правил, либо расширить существующие наборы.

**Comment by ovchinnikovdk** [comment]
@ChALkeR  Сделать проверку, а потом тоже добавить в тест-скрипт? Или необязательно, чтобы она была где-то видна?

**Comment by ovchinnikovdk** [comment]
@ChALkeR  У меня до этого была старая версия node.js и она отказывалась читать все с файла .eslintrc, поэтому я все перенес в gulpfile.js и все там написал.

**Comment by ChALkeR** [comment]
@ovchinnikov94 

> @ChALkeR Сделать проверку, а потом тоже добавить в тест-скрипт? Или необязательно, чтобы она была где-то видна?

Лучше сделать так, чтобы тесты на Travis не проходили при ошибках eslint.

> У меня до этого была старая версия node.js и она отказывалась читать все с файла .eslintrc, поэтому я все перенес в gulpfile.js и все там написал.

О, извините, пропустил. Лучше всего вынести всё-таки в .eslintrc (или .eslintrc.*, см. http://eslint.org/docs/user-guide/configuring#configuration-file-formats) — так редакторы с поддержкой eslint подхватят. Например, Atom.

**Comment by ovchinnikovdk** [comment]
@ChALkeR Выделил в отдельный файл, пришлось убрать правило "no-unused-vars", потому что валится на chai... А еще валится на module.exports = {...}, поэтому оставил по-старому. 
Eslint теперь запускается в скрипте  "test" перед выполнением основных тестов.

**Comment by ChALkeR** [comment]
@ovchinnikov94 А с чем конкретно валится на `module.exports = {…}`?

**Comment by ovchinnikovdk** [comment]
@ChALkeR то, что в {onlineUsers, wss ...} после, например, onlineUsers должно быть двоеточие, а не запятая

**Comment by ChALkeR** [comment]
@ovchinnikov94 https://github.com/babel/babel-eslint пробовали подключить? Даже в чате упоминалось, емнип.

**Comment by ovchinnikovdk** [comment]
@ChALkeR Исправил.
