### ISSUE TITLE
Bootstrap / jQuery не совсем место в проекте

### ISSUE THREAD

**Issue by ChALkeR** [ovchinnikov94/js_learn_node#5]
Подключите их либо из npm, либо из bower.

**Comment by ovchinnikovdk** [comment]
@ChALkeR Понятно как работает bower или npm, но не понятно как эти библиотеки будут доступны клиенту? Может мне для клиента отдельный проект создать и исключить все его файлы из репозитория?

**Comment by ovchinnikovdk** [comment]
@ChALkeR Вообще убрал клиентские файлы из проекта, чтобы не путаться с зависимостями.

**Comment by ChALkeR** [comment]
А, ну как хотите.
Их можно было веб-сервером статики раздавать, но у вас только API тут.
Можете в отдельный проект вынести клиент (чтобы был), и я его смотреть не буду, если не хотите =).
